### ISSUE TITLE
Spell progression for Dread Knight

### ISSUE THREAD

**Issue by eilersn** [ka-dyn/ExpandedContent#10]
Merging spellbooks is divisive, but maybe you would consider the following:

Changing the Dread Knight's spellbook so it allows for the casting of 10th level spells, if the caster level is high enough (Similar to how SpellbookMerge patches the Paladin's spellbook). Dread Knight is just the perfect fit for a melee Lich with a more divine (or rather unholy) twist on it. Even if you don't allow the merging in the standard Wrath interface, the patched spellbook would allow users to merge the spellbooks with Toybox, if they so choose.

Either way, great mod.

**Comment by bittercranberry** [comment]
I will not change it for now as the Dreadknight is not a full caster, and Owlcat keep changing the merged spellbook stuff. But I will have a look once I am confident Owlcat will not just change stuff again.
