### ISSUE TITLE
2 bugs with invoke deity

### ISSUE THREAD

**Issue by KTVSUN** [ka-dyn/ExpandedContent#103]
**Describe the bug**
1. If using bubble buff you can select an unlimited amount of domains and effectss, no matter how many cast of the spell are available to you. 
2. If selecting weather as a domain the character locks in turn-based mode when his turn comes. 

**To Reproduce**
1. Buff with bubble buff, you ll be able to apply as many domains as you want even with no cast available 
2. Cast the weather domain

**Comment by bittercranberry** [comment]
Not sure about bubblebuff but I believe the 2nd issue is fixed, after the next update could you please test it on your end to make sure it's not something else causing it?
That update should be out either today or tomorrow.

**Comment by KTVSUN** [comment]
sure will do

**Comment by KTVSUN** [comment]
the weather domain thing is working

**Comment by bittercranberry** [comment]
Nice, I'm going to close this as the 1st issue is most likely an issue in bubblebuffs.
Thanks for checking the spell for me :)
