### ISSUE TITLE
Suggestion: Modified Fighter Types

### ISSUE THREAD

**Issue by Zakna69** [ka-dyn/ExpandedContent#106]
Subtype Archer: I think the same Proficiencies like the Spear Fighter would fit. Maybe + Precision Shot 
Subtype Aldori-Defender: Own Proficienses by removing out of Fighter Tower Shield, Medium and Heavy Armor, adding Duellsword and Dodge

**Comment by bittercranberry** [comment]
No sorry, I am following the tabletop rules as close as possible when adding tabletop features.
If you want extra feats for free, you can add them using toybox.
