### ISSUE TITLE
Suggestion - New Feat - Arcing Weapon (Combat)

### ISSUE THREAD

**Issue by Ardencroft** [ka-dyn/ExpandedContent#107]
was printed in Chronicle of Legends as a feat for Eldritch Knight, one of the last books they put out. Think some 15-20 or 12-20 (with trickster) Innervations would be super fun to try out. Text of feat is:

Arcing Weapon (Combat)
Source [Chronicle of Legends pg. 8]
You can send magical blasts through your weapon.

Prerequisites: [Diverse training class feature.]

Benefit: As a standard action, you can cast a ray spell that requires a ranged touch attack and deliver the effect through your melee weapon, either through a melee attack or as a ranged attack. If you deliver this spell as a melee attack, this functions as the [magus spellstrike ability]. If you deliver the spell as a ranged attack, the spell is a ranged touch attack that discharges from your weapon and applies the weapon’s enhancement bonus to the spell’s damage. When fired in this way, the spell uses the weapon’s critical threat range, but the spell effect deals only ×2 damage on a successful critical hit. You can use a ranged touch attack spell that targets more than one creature (such as [scorching ray]), but you make only one attack through your weapon to deliver one ranged touch effect; additional ranged touch attacks from the spell are wasted and have no effect.

**Comment by bittercranberry** [comment]
Sorry but dynamically adding spells to weapons is a thing I just don't have the will to do, as all features in the game that do that are hardcoded to Magus and I lack the ability to get them working with every class .
It is possible, just not my me.

**Comment by Ardencroft** [comment]
Would it be possible to have the crit range on ray portion work without an enormous amount of effort? feel like that alone is the best part of the feat and would by itself save a whole prestige class lol
