### ISSUE TITLE
Impossible Domain Mythic Power Update?

### ISSUE THREAD

**Issue by Ardencroft** [ka-dyn/ExpandedContent#108]
Defense subdomain not selectable with impossible domain mythic power.

**Comment by bittercranberry** [comment]
It is in the impossible subdomain mythic power, if it is not there please reopen this ticket and post a screenshot to show the problem.

**Comment by Ardencroft** [comment]
https://i.imgur.com/8aPtUsI.png

I didnt know it existed, because you cant select it by default. It seems to be locked requiring 2 mythic path choices to choose one of the subdomains
