### ISSUE TITLE
Archon Subdomain - Law Shield of law misspelled

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#110]
**Describe the bug**
In the list of Domain Spells for the Archon Subdomain - Law shield in shield of law is misspelled as sheild. 
**To Reproduce**
Look at the Archon Subdomain - Law, check the domain spells and notice that shield is misspelled. 

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/a4871552-1d11-468d-8237-eb70bd9435f9)

**Comment by bittercranberry** [comment]
Fixed for next update.
