### ISSUE TITLE
Request to Add Psychic Class

### ISSUE THREAD

**Issue by caloyers** [ka-dyn/ExpandedContent#113]
Just maybe if possible you could add a psychic class just like in the Call of the Wild, or add a Time Mystery for the Oracle class

Thanks

**Comment by bittercranberry** [comment]
[Copied from Discord]
I'm not going to add any off the classes from that book until I run out of other stuff to add. Once I add one I'd want to do the rest and my todo list is too big for that already.

I won't add Time Mystery without Time Stop, and I currently lack the patience to try to that spell to work.
