### ISSUE TITLE
Divine Scourge can not choose Major Hexes

### ISSUE THREAD

**Issue by nextentlligods** [ka-dyn/ExpandedContent#116]
**Describe the bug**
Divine Scourge can not choose major hexes.  At the level 11th, the selections of the add major hexes can be seen but not selectabale; the character does not meet the prerequisites. Plz make Divine Hexes selections can be selected without prerequisite or  just add Major Hex feature to the archetype.

**Comment by bittercranberry** [comment]
Thanks for the report!
Fixed in next update.
Will close issue on release, sometime in next 2 days.
