### ISSUE TITLE
Warpriest Artifice Blessing wrong Gods

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#119]
**Describe the bug**
The Artifice Blessing for the Warpriest is not working correctly, so deities that have the Artifice domain are not getting the option and deities with the Tactics and Blood Subdomains are. I might be wrong about the blood Subdomains as Zura does not have access to the Artifice Blessing but I am not sure.  

Some examples are below. 
The gods I have listed below are not all of them but just some I could finds there are probably more.   
Deities that are missing the blessing are Atlach-Nacha, Apsu, Mammon, Khepri, Daikitsu, Yaezhing, Findeladlara, Yuelral, Torag.  
Deities that have it but are not supposed to are Achaekek, Zyphus, Fumeiyoshi, General Susumu, Deskari, Gorum, Iomedae, Sekhmet.       

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/6cbcfc19-986f-4cb5-8482-a3fb9706210a)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/4ca0f140-a217-4907-95e7-b283f55f3c1a)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/7541431b-f7ce-4153-afc4-115efbb7023f)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/2e541ea6-38fe-48dc-b3b5-4f960049a877)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/c272e2eb-934d-4943-a68a-8d35b72dfe78)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/c0409d2b-363a-485c-bc3b-32d34a30c479)

**Comment by bittercranberry** [comment]
Thanks for the report!
I've done a hotfix, so redownloading the mod will fix the issue.
