### ISSUE TITLE
Suggestion: Add Shield Brace Feat as part of Shield Mastery

### ISSUE THREAD

**Issue by TwentyGaugeHigh** [ka-dyn/ExpandedContent#120]
https://www.d20pfsrd.com/feats/shield-mastery-feats/shield-brace-combat-shield-mastery/

God bless you and keep you for adding Spear Fighter

**Comment by bittercranberry** [comment]
Glad that you like Spear Fighter!

The feat you are asking for is in this mod by Kurufinve.
https://github.com/ScaredKurufinve/Way-of-the-shield

**Comment by TwentyGaugeHigh** [comment]
i love you
