### ISSUE TITLE
Paladin Silver Champion missing space

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#121]
**Describe the bug**
The Silver Champion description is missing a space after the sentence ending with "mere words.".

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/b599fe71-15d0-4b30-88e7-d2d725ad51d8)

**Comment by bittercranberry** [comment]
I keep doing that.
I'll have it fixed for the next update, thank you for reporting.
