### ISSUE TITLE
Crimson Templar Prestige Class 

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#122]
Would it be possible to add the Crimson Templar Prestige Class? Ragathiel is one of my favourite deities and I would like if the class could be added. I have no idea if it is possible to create this class in game but it is a suggestion I would like to see at some point.

**Comment by bittercranberry** [comment]
Added in this mod, https://github.com/YLMstring/PrestigePlus/tree/v2.0.0
