### ISSUE TITLE
Angelfire Apostle Evil and Neutral Deities

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#123]
**Describe the bug**
An Angelfire Apostle should only be able to chose good deities but I can select Evil and neutral deities added by this mod. 

**To Reproduce**
Create an Angelfire Apostle and select one of the evil or neutral deities added by this mod.  

**Expected behavior**
An Angelfire Apostle should be unable to choose Evil and neutral deities. 

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/eaab9d4e-bc34-4e7e-a122-d60c82959fae)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/97312ce5-3584-4357-9beb-0059e091017d)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/53bec068-ab45-45c6-a11f-1496ec6f3442)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/4ee6eaba-18fe-4f2a-b65c-4ae2308fc1dd)

**Additional context**
I have Mystical Mayhem installed.

**Comment by bittercranberry** [comment]
Thanks for the report.
As this shouldn't cause any issues, I'll fix it for the next big update (around dlc5 release).

**Comment by bittercranberry** [comment]
Fixed in v0.8.01
