### ISSUE TITLE
Urban Druid Domain Text Missing paragraph breaks

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#124]
**Describe the bug**
The descriptions for the Urban Druid Domains are missing paragraph breaks. 
**To Reproduce**
Create an Urban druid and look at the domains. There should be paragraph breaks used. Only the Weather Domain has the text laid out correctly. 

**Screenshots**
The last picture shows the Weather Domain which has the description laid out correctly. 
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/c094f5f1-3955-4c6b-ae4e-1abb358671bc)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/b2fae874-2113-4664-9f36-4c865a90fb4b)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/9d921493-a115-4291-a8b7-912542cd4150)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/47fcf0bd-a832-412c-9be8-140ebcfeb5ee)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/2c6f69c8-cb2a-4db9-9de0-11b77788ef48)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/f03eff12-91c2-4dcf-a54f-51545bd68319)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/675df866-a33e-499a-9296-13942413de00)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/a7d11362-ff3b-49be-9ea3-4e700e37da38)

**Comment by bittercranberry** [comment]
Thanks.
I'll have this fixed for the next update, most likely after the next DLC launch.
