### ISSUE TITLE
Korada Description missing space between Open and Hand 

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#126]
**Describe the bug**
The sentence ending "of the OpenHand of Harmony" near the bottom of the screenshot is missing a space between Open and Hand.  

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/a00f5aa6-db53-47e3-9b17-69087c25518b)

**Comment by bittercranberry** [comment]
Thanks
Fixed in next update.
