### ISSUE TITLE
Add Elemental Lords

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#128]
**Describe the solution you'd like**
Add the Elemental Lords Ayrzul, Hshurha, Kelizandri and Ymeri as Deities. All of them are 1E and have official icons to use. Adding a new dropdown tab for them might be a good idea.     

**Additional context**
https://pathfinderwiki.com/wiki/Elemental_lord
https://pathfinderwiki.com/wiki/Ayrzul
https://pathfinderwiki.com/wiki/Hshurha
https://pathfinderwiki.com/wiki/Kelizandri
https://pathfinderwiki.com/wiki/Ymeri

**Comment by bittercranberry** [comment]
I'm closing these requests as they are just spamming up the issues page.
As I said before, I am adding gods when people ask for them, but everyone else has understood that to mean asking for the god they want to use.
I will most likely add some of these in the future, but please only ask for stuff you plan to play as each god does take about 20 min and you posted many many gods no-one else has ever mentioned to me.

**Comment by Lordmitch2** [comment]
I am sorry that was the last of the Gods I had in mind right now. I did plan on using them at some point. I just thought if I added them all at once it would be easier to keep track of. Do you want me to forget about them completely or ask again when I am about to create a character using them?
