### ISSUE TITLE
Sworn of the eldest domain abilities key of wisdom instead of charisma

### ISSUE THREAD

**Issue by DKemp98** [ka-dyn/ExpandedContent#130]
The number of uses of domain abilities that you get as a Sworn of the Eldest inquisitor is keyed of wisdom. A S.o.t.e. I play with wisdom below 10 and high charisma thus does not have access to the 1st level power. 

**To Reproduce**
Play a sworn of the eldest inquisitor

**Expected behavior**
I think domain abilities should also scale of charisma for s.o.t.e. 

> Whimsical Worship (Ex): A sworn of the Eldest uses her Charisma modifier, rather than her Wisdom modifier, to determine all class features and effects relating to her inquisitor class, including her spells, cunning initiative, and true judgment abilities.

![20231108182933_1](https://github.com/ka-dyn/ExpandedContent/assets/56640886/f84e9964-e84f-4111-90a9-dbfa994ab055)

**Comment by bittercranberry** [comment]
Fellow modder AlterAsc added the archetype for their own use, and between us we could not figure out a way to make the stat conversion work without completely remaking every single domain.
As Alter was fine with Wisdom, so we left it that way.
