### ISSUE TITLE
An issue prevented me from entering the game

### ISSUE THREAD

**Issue by 1axw2** [ka-dyn/ExpandedContent#135]
If I use both TabletopTweaks-Base and ExpandedContent and take off the "Feats" in TabletopTweaks-Base, I won't be able to play the game. When the game enters, the load will stop at about 70% of the position.

**Comment by bittercranberry** [comment]
That makes sense, for compatibility I have to edit some of the TTT options, so turning them off can break things.
For now just use TTT default settings, but if you screenshot your disabled options I can put a safeguard so the game still loads in a future update.

**Comment by 1axw2** [comment]
> 这是有道理的，为了兼容性，我必须编辑一些 TTT 选项，因此关闭它们可能会破坏事情。现在只使用 TTT 默认设置，但如果您截取禁用的选项，我可以设置保护措施，以便游戏仍然可以在未来的更新中加载。

如果能说明编辑了哪些选项就好

**Comment by 1axw2** [comment]
> 这是有道理的，为了兼容性，我必须编辑一些 TTT 选项，因此关闭它们可能会破坏事情。现在只使用 TTT 默认设置，但如果您截取禁用的选项，我可以设置保护措施，以便游戏仍然可以在未来的更新中加载。

如果能说明编辑了哪些选项就好，谢谢你的回复

**Comment by bittercranberry** [comment]
Many sections have been edited, this is why I ask for screenshots of your settings, it is much easier for me to troubleshot that way.

I you just need the game to run, reset the TTT settings to default.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
很多部分都被编辑过，这就是我要求您提供设置截图的原因，这样我更容易排除故障。

如果您只需要运行游戏，请将 TTT 设置重置为默认。

**Comment by 1axw2** [comment]
> 许多部分都经过编辑，这就是我要求您设置截图的原因，这样我更容易进行故障排除。
> 
> 我只需要游戏运行，将TTT设置重置为默认值。
> 
> 很多部分都被编辑过，这就是我要求您提供设置截图的原因，这样我更容易排除故障。
> 
> 如果您只需要运行游戏，请将 TTT 设置重置为默认。

我只测试了一次性关闭了所有“专长”的内容会导致这个问题，没有做额外的测试，很抱歉没办法提供具体设置的截图
I only tested the content that turned off all“Expertise” at once, which caused this problem. I didn't do any additional testing, and I'm sorry I couldn't provide a screenshot of the specific settings
