### ISSUE TITLE
Background: Archduke of Cheliax

### ISSUE THREAD

**Issue by Seinra** [ka-dyn/ExpandedContent#137]
**Describe the bug**

Archduke of Cheliax doesn't add the INT bonus to both Lore skills in the Total skill level.

**To Reproduce**
Steps to reproduce the behavior and expected behavior:

At creating a new character with stats STR: 7 | DEX: 16 | CON 14 | INT: 19 | WIS: 7 | CHA: 14 and adding the skill points to both knowledge and lore skills, the four of them should end with a Total +10 (+4 INT bonus, +3 Class bonus,  +1 Trait background bonus, +1 Other background bonus), but both Lore skills have a Total +4 instead of a Total +10.

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/7744272/3c184d08-c29c-4a76-88d2-35782b0ff28c)
![image](https://github.com/ka-dyn/ExpandedContent/assets/7744272/ffcf544f-627e-4a7b-a918-776ab1415ee9)

**Additional context**
It works as it should (without the bug) after upgrading the Lore skills to level 3.

**Comment by bittercranberry** [comment]
Looks like it works fine, unfortunately the base game has trouble displaying the correct number.
