### ISSUE TITLE
Ice Subdomain not available via Impossible Subdomain for Channeler of the Unknown.

### ISSUE THREAD

**Issue by CaptOcto** [ka-dyn/ExpandedContent#138]
**Describe the bug**
Created a level 20 mercenary in main WotR campaign and all the leveling up was going fine until I tried to take Impossible Subdomain: Ice and I can't find it anywhere.

**To Reproduce**
1. Create a Channeler of the Unknown.
2. Take Impossible Domain: Any.
3. Open Impossible Subdomain selection screen.

**Expected behavior**
Should be able to take Ice Subdomain with Impossible Subdomain.

**Screenshots**
![202402071420532262](https://github.com/ka-dyn/ExpandedContent/assets/119921959/40a3d161-189a-4225-96d1-4e2cfb75860e)

**Additional context**

**Comment by bittercranberry** [comment]
Fixed
