### ISSUE TITLE
Extra Discovery DLC feat

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#139]
**Describe the bug**
The Lord of Nothing DLC added the Extra Discovery and Extra Discovery (vivisectionist) Feats, when choosing these feats, the discoveries added by this mod Healer's Touch and Pheromones are not available for selection. 
Also the vivisectionist can't choose Healer's Touch and Pheromones when selecting a Medical Discovery.  

**Expected behavior**
Healer's Touch and Pheromones be available when choosing the DLC feats.  
The vivisectionist can choose Healer's Touch and Pheromones when selecting a Medical Discovery.

**Comment by bittercranberry** [comment]
Fixed in next update. However Vivisectionist will not get Healers Touch added to their version of the feat.
