### ISSUE TITLE
Touch of profane corruption cruelty DC doesn't scale/ scales incorrectly 

### ISSUE THREAD

**Issue by ProximityValue** [ka-dyn/ExpandedContent#14]
The DC for Touch itself lists as normal, but the DC against any of my cruelty effects is always 11 

**To Reproduce**
I'm a dread knight conqueror lvl 11 with lich mythic 3

**Expected behavior**
Expected the DC to be 22 without temporary buffs 

**Additional context**
Using ToyBox I messed around with my characters stats, nothing seemed to affect the cruelty DC

**Comment by whisper2053** [comment]
This is an issue that I have been running into as well. To add to it, I'm finding that the cruelty effects (when toggled to 'on' status) tend to also proc on pretty much everything. For instance, as an Arcanist/Dread Knight with Stunning Barrier cast, anyone striking my character and proc'ing the stun also gets to make a save against the cruelty. This seems to extend to any/all sort of active action (charge, spell casting, healing effects, channel energy, etc). Everyone gets to make a DC 11 save in addition to whatever else is going on. It's intriguing!
