### ISSUE TITLE
Archduke of Cheliax Initiative

### ISSUE THREAD

**Issue by Vilacard** [ka-dyn/ExpandedContent#141]
From my understanding of the wording, you should be getting your initiative based on intelligence instead of dexterity. Currently it seems like I gain both. With 19 dex, 20 int, and archduke of cheliax I have +11 initiative when I think I should only have +7.

https://i.imgur.com/nhv8Jhp.png

**Comment by bittercranberry** [comment]
Fixed for next update. Probably.
