### ISSUE TITLE
Drake Rider Char shows Mulitple Instance when choosing Camping Roles

### ISSUE THREAD

**Issue by Gyrados15** [ka-dyn/ExpandedContent#142]
When I choose camping roles (Cooking, Lookout etc) the Drake Rider seems to show up Multiple Times instead of only Once in Each Role (Screenshot below), if I try select one of these Duplicates the game Hangs then CTD's

![image](https://github.com/ka-dyn/ExpandedContent/assets/129967365/8cdf8f37-7b09-4bf6-b561-0873f2148da4)

In my case, the Drake Rider also has Levels in the Silver Champion Paladin Class, not sure if that affects anything, but it is my first time using both classes.

**Comment by bittercranberry** [comment]
Before I get a chance to look into this there are two things yoh could do which will help a lot.
First, use Toybox to respec your character, picking the same build to see if the bug is still present.
Second, respec as random stuff to see if that fixes it.

I won't be able to look into this until Thursday so good luck!

**Comment by Gyrados15** [comment]
Happy to do it, just for clarity before the update this char was a totally
different Paladin Class and Gendarme Gestalt prior to the update, I
installed the update them did a respec into Silver Paladin+ Drake Rider :)

**Comment by bittercranberry** [comment]
Oh also please test the above stuff without Gestalt, I don't understand it and the code for it is eldritch enough for me to not try.

**Comment by bittercranberry** [comment]
I cannot replicate this bug, this issue will be closed on Monday if no one experiences the bug while not using gestalt.

**Comment by Gyrados15** [comment]
Epic Thanks for trying! Not sure what happened the first time for  but it
was fine after a respec as you suggested

**Comment by bittercranberry** [comment]
Good to hear!
If you find anything else acting strange, please let me know.
