### ISSUE TITLE
Conqueror Unable To Take Advanced Rage Powers As They Have No Levels To Meet The Prerequisites

### ISSUE THREAD

**Issue by Vaeliorin** [ka-dyn/ExpandedContent#144]
**Describe the bug**
Dread Knight Conqueror can only take basic rage powers since they have no levels to meet the prereqs for more advanced rage powers.

**To Reproduce**
Level up a Conqueror to level 12+ and try to take anything more than a basic rage power

**Expected behavior**
I'm not certain if this is intentional or not.  I'd have expected to be able to take advanced rage powers, but since I'm not sure what archetype this was based on, I'm not sure how to check.

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/122745498/40090672-ff80-4db2-ad51-9970a568801e)

**Comment by bittercranberry** [comment]
Dreadknight was all Kadyn homebrew, but I have always read it as not being able to get the advanced powers.
