### ISSUE TITLE
Unity NullReferenceException

### ISSUE THREAD

**Issue by Gyrados15** [ka-dyn/ExpandedContent#145]
Righto so I updated the Game itself on Steam and then this mod to 0.9.50, but in the Logs, I'm seeing this : 

[328,8391 - Unity]: NullReferenceException: Object reference not set to an instance of an object
ExpandedContent.Config.ModSupport+BlueprintsCache_Init_Patch.Postfix () (at <9626326838bd4569944bea6013e857d1>:0)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Kingmaker.Blueprints.JsonSystem.BlueprintsCache.Init_Patch207(Kingmaker.Blueprints.JsonSystem.BlueprintsCache)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition.Kingmaker.Blueprints.JsonSystem.StartGameLoader.LoadPackTOC_Patch11(Kingmaker.Blueprints.JsonSystem.StartGameLoader)
Kingmaker.GameStarter+<StartGameCoroutine>d__28.MoveNext () (at <95842a8b72b4464786c5ce2630f0c9e5>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext () (at <4fae2288737c4dfda349689bbefabfcc>:0)

The Unity Mod Manger is version  0.27.14.0

**Comment by AlistairKion** [comment]
The update appears to have made this mod incompatible with PrestigePlus, from my testing, and results in the that error.
Do you also have that mod installed?

**Comment by Gyrados15** [comment]
I do run that mod aswell yea

**Comment by bittercranberry** [comment]
Fixed in last PP+ update
