### ISSUE TITLE
Unable to select Achaekek (Mantis God) as a deity

### ISSUE THREAD

**Issue by Valor6** [ka-dyn/ExpandedContent#146]
**Describe the bug**
When creating a character, I'm unable to choose Achaekek as a deity. It will show up as an option on the right hand side when I hover over 'Gods of the Inner Sea' drop down, but it will not be an option. This may be due to the fact that he's now a vanilla deity. He is also not chooseable with the vanilla deities, it's like he's vanished.

**To Reproduce**
Seems to happen in character creation no matter the other choices I pickl.

**Expected behavior**
Because of the addition of the Vanilla Mantis Warpreist, you are required to follow Achaekek. However, with this mod activated I'm unable to choose the deity in order to play the class properly. (I believe I can still choose from the other added deities, since the game doesn't block them out.)

**Screenshots**

**Additional context**
As stated above, it's possible the addition of Acahekek as a vanilla deity and this one adding him in conflict somehow.

**Comment by bittercranberry** [comment]
Fixed in next update
