### ISSUE TITLE
Revelation Wood Bond gives circumstance instead of competence bonus

### ISSUE THREAD

**Issue by Christoph-Wagner** [ka-dyn/ExpandedContent#147]
**Describe the bug**
The Revelation "Wood Bond" of the "Wood" Mystery gives a "circumstance" instead of "competence" bonus to attacks. At least as Ravener Hunter.

**To Reproduce**
Create a character with woodbond, equip a quarterstaff, check attack bonus in charactersheet

**Expected behavior**
The in-game description and RAW both say competence.

**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/1609329/5b4cd08d-f9ab-4d07-a856-19074e5d4ef7)

**Additional context**
https://www.d20pfsrd.com/classes/base-classes/oracle/mysteries/paizo-oracle-mysteries/wood/
https://github.com/ka-dyn/ExpandedContent/blob/master/ExpandedContent/Tweaks/Mysteries/WoodMystery.cs#L719

**Comment by bittercranberry** [comment]
Thanks for the report!
Fixed internally and will be in the next update, will leave this ticket open until then.
