### ISSUE TITLE
Bleesed Dragon (Umbral Oposite) 

### ISSUE THREAD

**Issue by picninim** [ka-dyn/ExpandedContent#148]
I really would like to have a "Blessed" type dragon companion, that would antagonize with the Umbral.
I know that might not be lore friendly, and even OP. But would be a good companion for healer based chars and role play :)

**Comment by bittercranberry** [comment]
No sorry, I have added all the drake types planned for now.

**Comment by picninim** [comment]
That's alright. It's already a great mod. Thanks for it :)
