### ISSUE TITLE
Breaks the game and saves after the new update

### ISSUE THREAD

**Issue by Yanara126** [ka-dyn/ExpandedContent#15]
After the new update to 1.2 having the mod installed makes booting up the game impossible. It loads to about two thirds of the loading bar and then gets stuck. Not having the mod installed however breaks all saves in which it was installed. The main menu opens normally, however when you try to load a save, it loads to about seven percent, the screen goes black and it shows the main menu again.

**Comment by Shadewarp** [comment]
Any chance of this getting fixed?

**Comment by RozielTheCorporal** [comment]
I beg the Sarenrei to bless the hearts of creaters to update this mode...
...i kinda wanted to make a Lich-antipaladin=3
