### ISSUE TITLE
Osiris Wrong title, Set missing space and Horus description

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#150]
**Describe the bug**
Osiris's has the wrong titles, it should be Lord of the Living.
In Set's description after Set Vying the words to steal are missing a space and are instead "tosteal", look at the last line at the bottom of the picture to see what it mean. 
**Screenshots**
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/d1fd423a-d1c9-4733-a7ef-42f0bfd00742)
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/12a85d5c-5578-4462-a621-4ad6eb55ed7b)

**Comment by Lordmitch2** [comment]
In Horus's description, after "An ally of Osiris and Isis" there is a space before the comma. Also the word churches in the last line has a space between churche and the s written as "churche s".  
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/4f342861-482d-4484-b048-1ef7e7a8dfd9)

**Comment by bittercranberry** [comment]
Thanks for the report, I'll have these fixed for the next update.

**Comment by bittercranberry** [comment]
Fixed most of these, left the hyphens as they look fine to me as instead of using   ,   they refer to the previous section.

Will be in next update.

**Comment by Lordmitch2** [comment]
Here some more bugs for gods. Some spelling mistakes and the wrong favoured weapon for some gods.
Lady Nanbyo gives the wrong favoured weapon, giving a quarterstaff instead of a Warhammer. 
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/6ed6a630-c8af-4ae2-acc4-087049cac2bc)
Nalinivati gives the wrong favoured weapon, giving a quarterstaff instead of a Sai. 
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/987076f7-fd8d-456b-8a0e-4aaed1d4bdc0)
Tsukiyo has a missing space.
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/fbbd4c5f-124e-4ec8-84d4-1b43d57d64ef)
Yamatsumi has make missing the m.
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/17be2067-8d9e-410b-bec6-c917eb3a1b3c)
Nalinivati gives the wrong favoured weapon, giving a quarterstaff instead of a Rapier. 
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/2038c16c-41c6-4d9c-ab87-87827e4c3daa)
Varg has Greataxe misspelled as Greataxw.  
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/f1d767d6-505c-4ba6-af22-6ee43ba9df0b)
Verex has Battleaxe misspelled as Battleaxw.  
![image](https://github.com/ka-dyn/ExpandedContent/assets/47829580/bbe60a39-1efb-4f44-aff4-fb0794974272)

**Comment by bittercranberry** [comment]
All fixed
