### ISSUE TITLE
The mod integration with Prestige Plus no longer works

### ISSUE THREAD

**Issue by force200** [ka-dyn/ExpandedContent#152]
The game refuses to load when both Prestige Plus and Expanded Content are installed.

**Comment by force200** [comment]
> Make sure mods and UMM are up to date

They are

**Comment by bittercranberry** [comment]
Check update numbers, give me screenshots, maybe post a log?
Just saying "Game not load" when it loads for other players is not helpful.

**Comment by force200** [comment]
I just double-checked everything and noticed that it was a screw up on my part. I messed up something with UMM, so that the update for prestige plus didn't install properly and I was still running an oder version. I re-installed the latest version and everything started working again.
