### ISSUE TITLE
Stargazer Sidereal Arcana: The Follower is not working

### ISSUE THREAD

**Issue by NakedGranny** [ka-dyn/ExpandedContent#154]
Stargazer "The Follower" feature is not protecting against negative levels bestowed by Nabasu demons through their Enervate SLA.

1. Gain levels in Stargazer until you can pick up a Sidereal Arcana feature
2. Select "The Follower" - it's supposed to make you immune to all negative energy / energy drain effects caused by Demons (this specifically includes negative levels, such as those bestowed by Enervate spells / SLAs)
3. Find a Nabasu demon (the one in the ghoul pool in the dungeons beneath Drezen during chapter 2 will do)
4. get him to cast Enervate at you - it will still bestow temporary negative levels just as normal, even though it should not (Death Ward spell buff will prevent it, for example)

The feature does specify that it's supposed to only protect you from effects originating from Demons. But Nabasu are demons. Their abilities and spells are not supposed to be able to affect you with negative levels (such as by Enervate when they cast it)

Just for clarity, the +4 saving throw bonus is not supposed to be restricted to only apply against effects originating from demons, but the Enervate spell does not allow a saving throw (it only tests against Touch AC and Spell Resistance).

**Comment by bittercranberry** [comment]
I can make a fix for that tonight, but I will be unable to test it myself for a while.
If you are on the Owlcat Discord, ping bittercranberry and I'll send you the fix to test.

Or just wait a couple of weeks, up to you :)

**Comment by bittercranberry** [comment]
Fixed
