### ISSUE TITLE
Suggestion: Lightning subdomain

### ISSUE THREAD

**Issue by R2162** [ka-dyn/ExpandedContent#156]
Hello, 
I quite enjoy the storm druid, however some of the current domains in the game are somewhat underwhelming. I think it would be a great boost to the storm druid if they could use the lightning rod ability for a on the go empower basically.

**Comment by bittercranberry** [comment]
I did try to add this back when I added the storm druid, but at the time it was beyond what I could do.
I'll have another look at some point.

**Comment by R2162** [comment]
Thanks for the consideration

**Comment by bittercranberry** [comment]
In next update, will close ticket after I've tested and released.
