### ISSUE TITLE
Interraction issues with TTT

### ISSUE THREAD

**Issue by nextentlligods** [ka-dyn/ExpandedContent#157]
If alternative capstone in TTT enabled, oracles with newly-added mysteries (such as succor, wood etc.) cannot get its final revelation at lv 20.
it seems that ttt modifies the oracle progression and hide the final revelation, perhaps changing the priority can fix it?

**Comment by bittercranberry** [comment]
Is it not one of the options in the capstone selection? 
(Can't use PC at the moment to check)

**Comment by nextentlligods** [comment]
I only find none except the vanilla final revalations. TTT changes to remove the fina lrevalations and give the final revelation selection so you can regain it, but the option only contains those of vanilla. I can ensure that using Toy of box.  So if an oracle with newly-added  mysteries chooses the  final revelation option of alternative selection, the options is empty.

**Comment by bittercranberry** [comment]
Not sure what could be causing this, here is it working fine in my game.
![image](https://github.com/user-attachments/assets/225eb892-bd28-46c0-bc56-58d75a512d32)
Could you answer these to help me troubleshoot?
What archetype is the Oracle?
Are all mods up to date?
If you fully respec, does the issue persist?

**Comment by nextentlligods** [comment]
![Screen](https://github.com/user-attachments/assets/4b271753-ad6d-48f4-9c37-d09df6fce407)
You can see the oracle without any archetype with succor mystery cannot get any final revelation.
1. no archetype
2. yes at least via ModFinder
3. I create a new character, and the screen shot show that.
I searched the final revelation using Toy of Box, and couldn't find the feature of the matching mystery. There are only vanilla capstones.

**Comment by nextentlligods** [comment]
![Screen](https://github.com/user-attachments/assets/e4c8f746-3da1-42d6-9058-0eb59e077274)

You can see the oracle without any archetype with succor mystery cannot get any final revelation.
1. no archetype
2. yes at least via ModFinder
3. I create a new character, and the screen shot show that.
I searched the final revelation using Toy of Box, and couldn't find the feature of the matching mystery. There are only vanilla capstones.

**Comment by bittercranberry** [comment]
Interesting, I know it's not TTT, P+, CO+, Summoner, and some others I don't remember as I'm not at the PC.

If you do track it down to a single mod I will try to fix it, but as far as I know it works with all of the more common mods.

**Comment by nextentlligods** [comment]
It's [EnduringRework](https://github.com/alterasc/EnduringRework). It's abolutely unexpected...

**Comment by bittercranberry** [comment]
Weird, I'll ask Alter when I have a moment, thanks for the investigation.

**Comment by bittercranberry** [comment]
Alter was unable to replicate the issue, and neither was one the people that helps me test stuff.
