### ISSUE TITLE
New Plant Companions only level 16

### ISSUE THREAD

**Issue by Philemon5** [ka-dyn/ExpandedContent#159]
**Describe the bug**
My plant companion only get to level to level 16 when i play treesinger and picked sapling companion instead of domain

**To Reproduce**
Level up as treesinger druid archetype and pick companion over domain.

**Expected behavior**
The companion should reach level 20.

**Comment by bittercranberry** [comment]
If you are the guy from nexus please do not open a ticket in 2 places at once. In case you are not, do not worry it is a TTT option and the game is better this way as pets are to strong.

**Comment by Philemon5** [comment]
Thank you for the additional information regarding this issue.
