### ISSUE TITLE
Suggestion: Drake Companion stats

### ISSUE THREAD

**Issue by Philemon5** [ka-dyn/ExpandedContent#160]
Drake Companions should get the innate animal companion bonus stats, or otherwise be sompensated. 8 dex baseline without any mythical feats and bonuses is just too low for a fully grown drake. Even the hypogriph gets the animal companion bonus stats.

The game wiki says the following on this topic: 
Animal companions gain +2 natural armor and +1 Strength and Dexterity at 1st level, at 3rd level, and every three levels thereafter, up to +14 natural armor and +7 Str/Dex at 18th level.

**Describe the solution you'd like**
Give drake companions innate companion stats or other compensations so they dont end up weaker than other animal companions.

**Describe alternatives you've considered**
Compensate drakes stats in other ways.

**Comment by Destinycallsyou** [comment]
without knowing anything about this scripting language, having rigged some mod (with asking for permission ofc) i can already tell that its the " animalcompanionRank " modifier that adds this feature after taking a looksie in the files. i guess getting 14 natural armor ontop of the ac bonuses you provided might be alot. my suggestion would be to make the +2 bonuses in class progression of drake companions +1s and then adding this companion rank feature on it. if you think thats is op i would love to have a chat about this with you. i was looking for discord but coudnt find one. Hope you have a great day , much love

**Comment by Philemon5** [comment]
you implemented the rules correctly after reading the core rules on this subject i close this suggestion. if you still wan to get in touch with me id like it , was searching for your discord. ggs
