### ISSUE TITLE
Please add Flying Charge to drake mounts 

### ISSUE THREAD

**Issue by Vannner013** [ka-dyn/ExpandedContent#164]
First of all, this mod is incredible, almost perfect! i love it and thank you for it! :D

Since now we have sable marine and the flying charge mechanics, could we have a way to get it for our drake pets, with proper animations?

Doesn't matter if added as a class ability, as a drake ability or through the drake mythic ability, i think its the last thing to make them absolotely perfect! (and a skeletal/ravener dragon model for lich undead mount, but that's not the point of this request '^^)

**Comment by bittercranberry** [comment]
Glad you like the mod!

I'm not adding anything else to the drakes as I consider them done (at least for now), and also I don't think the animation for the charge would look good enough for me to want to release in an update.
You may be able to use Toybox to give the drakes the flying charge, but I have no idea if it will work.

Like 10 people asked for a Lich drake but I don't want to add it; the Umbral Drake was me trying to meet people in the middle so please try that.
