### ISSUE TITLE
Overlap with Tabletop Tweaks: Base 

### ISSUE THREAD

**Issue by hauntsthisshell** [ka-dyn/ExpandedContent#166]
Hey, just wanted to point out that "tabletop tweaks: base" adds its own version of the "inflict pain" spell. So when using both mods together you get two versions of the spells. Its a nonissue, but I noticed that you have toggles for other spells in the mod, so you may want to add one for "inflict pain." 

Thanks for your hard work!

**Comment by bittercranberry** [comment]
I don't disable my spells as it would mess with other linked features like domains.
Plus I added mine first :P
