### ISSUE TITLE
Silver Champion and Claw of the false Wyrm god selection 

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#168]
**Describe the bug**
The Silver Champion and Claw of the false Wyrm can chose the wrong gods.
The Claw of the false Wyrm can chose Apsu and Norgorber. 
The Silver Champion can chose Lady Nanbyo. 

**Screenshots**
![image](https://github.com/user-attachments/assets/f610d7ae-c187-4487-b292-2782089c3122)
![image](https://github.com/user-attachments/assets/06c4b1bc-defb-4661-b0af-2f6572aca51a)

**Comment by bittercranberry** [comment]
Thanks, I'll fix for the next update
