### ISSUE TITLE
Disabling individual deities or categories of deities, breaks the portrait selection screen of the character creation UI

### ISSUE THREAD

**Issue by RendonGH** [ka-dyn/ExpandedContent#17]
Describe the bug:

If you utilize any of the UMM options to disable any god from the "deities" section added by this mod, it will render the portrait selection UI non functional. The portrait selection UI no longer changes portraits when selecting one, nor can you proceed by pressing the "Next" option. Disabling any of the Demon Lords or ArchDevils does not cause this problem. 

This problem persists without any other mods installed, but it does not seem to occur consistently. For example, I have been able to disable Ragathiel without causing any issue. However, upon a few consecutive restarts, the bug will appear eventually, and once it does, no number of times restarting the client will cause it to resolve itself. 

1. Launch Game
2. Open UMM menu
3. Attempt to disable a god from the deities section. 
4. Restart game client.
5. Attempt to create a new custom character and change their portrait. 

Expected behavior:

Selecting a different character portrait should change the maximized rendition of that portrait on the right side of the screen. It should also be possible to select other UI elements, such as the custom portrait button or the next button on the bottom of the screen. 

Screenshots:
![image](https://user-images.githubusercontent.com/46346522/160968148-7f29d8a5-d654-4dd5-b1cd-03a8cb48ce6e.png)
![image](https://user-images.githubusercontent.com/46346522/160968172-ff55c8b7-8094-4f5d-be00-73e2ad598e7a.png)

Additional context:
The image of the portrait selection UI is an example of the character creation UI bugging out. The UMM options displays the settings I have disabled in the Deities submenu to produce this result. 

I've included my game log in the hopes that it helps diagnosing the issue. A possibly relevant exception referencing deities may be found at the bottom of the text file. 
[GameLog.txt](https://github.com/ka-dyn/ExpandedContent/files/8385736/GameLog.txt)

**Comment by irishbear28** [comment]
This behavior isn't exclusive to the deities, I had the same thing happen and I simply closed the UMM dialogue on boot up, I did correct the behavior however by switching from Fullscreen to windowed borderless

**Comment by bittercranberry** [comment]
Removed the ability to disable individual gods for now as it causes issues with Paladin, will add readding the feature to the list of things to do.
