### ISSUE TITLE
Mythic inspiration not working with evangelist

### ISSUE THREAD

**Issue by theduke59** [ka-dyn/ExpandedContent#172]
Mythic inspiration isn't working with evangelist.  It gives no bonuses.

I run dark codex and tabletop tweaks

**Comment by bittercranberry** [comment]
I don't add either of those things, does this issue happen without Expanded Content installed?

**Comment by theduke59** [comment]
I guess take this as a compliment that I assumed the class was implemented by your mod... Sorry!  I'll take my bs elsewhere

**Comment by theduke59** [comment]
Keep up the great work!

**Comment by bittercranberry** [comment]
Thanks :)
That archetype is from Homebrew Archetypes btw.
