### ISSUE TITLE
Deity Selection and Alignment issues

### ISSUE THREAD

**Issue by Athos-E** [ka-dyn/ExpandedContent#19]
There are a few faiths bugged rn.

* Shelyn, which is supposed to be available to any Good alignment, isn't available when Respec'ing Sosiel. If you opt out Deity choice(or just don't respec), his spells become unavailable and the game claims he's at the wrong alignment. He is Neutral Good. Shelyn is available for Camellia, which is Neutral Evil.

* Green Faith, which I -believe- is to be available to all Neutral alignments (since it's a druidric faith) isn't available when respecing Camellia, but it is available for Sosiel.

* Lich Deity does not become unavailable at Deity Selection when you disable it at Unity Mod Manager. It also seems to not have an alignment restriction, since it is available for Sosiel.

* Iomedae is not available for Lawful Neutral alignment (tested with Lann).

* Calistria is not available for Chaotic Neutral alignment (tested with Woljif).

* Overall, above points out a few  of the deities have inverted alignment restrictions or don't have alignment restrictions that I could detect.

**Comment by FrijDom** [comment]
A few of these are because the game locks out features a character already has, such as Iomedae for Lann. Respec mods often don't properly remove the existing faiths, especially with Expanded Content.

**Comment by bittercranberry** [comment]
Issues should be fixed now, respecs must be done with the in-game method or with the Toybox Mod.
