### ISSUE TITLE
Lann worships wrong Sun goddess.

### ISSUE THREAD

**Issue by FrijDom** [ka-dyn/ExpandedContent#20]
**Describe the bug**
Lann worships Sarenrae instead of the correct Iomedae. This results in him erroneously not getting access to the War domain, while also giving him incorrect access to Healing and Fire.

**Comment by bittercranberry** [comment]
This is a bug left over from a old update, using Toybox to respec should fix the issue. If not you may have to use Toybox to remove the Sarenrae feature first.

**Comment by FrijDom** [comment]
I tried both of those, it didn't change anything.

**Comment by FrijDom** [comment]
Ah, I see the issue. I didn't notice the recent update.
