### ISSUE TITLE
Dread Knight issues

### ISSUE THREAD

**Issue by alterasc** [ka-dyn/ExpandedContent#21]
1. Sinful Absolution doesn't add damage. I think that's because it tries to find DK class blueprint, which is only created later.
2. Aura of Absolution bonus damage scales from character level, not class level.
3. Aura of Cowardice does not work.
4. Aura of Despair does not work.
5. Aura of Depravity does not work.

Testing was done in Underground Caves of Kenabres.

**Comment by bittercranberry** [comment]
Should be fixed in next update, I'll leave the ticket open just in case though.
