### ISSUE TITLE
Doesn't install correctly

### ISSUE THREAD

**Issue by SamuraiStrudel** [ka-dyn/ExpandedContent#23]
When I drag and drop the ExpandedContent-master into the UMM, it doesn't show the "ok" or even in the UMM menu in game. I tried extracting, zipping the ExpandedContent folder and dropping it in; that makes it show up as "Ok", but then it has !!! errors
[Player.log](https://github.com/ka-dyn/ExpandedContent/files/8950741/Player.log)
In the log it doesn't even mention the mod. I can't install it as the raw zip from github and the subfolder doesn't work either, I don't know what to do.

**Comment by bittercranberry** [comment]
Go to https://github.com/ka-dyn/ExpandedContent/releases/tag/v0.3.6 and download the .zip then drag that into UMM, if that does not work could you send me some screenshots please?

**Comment by SamuraiStrudel** [comment]
I misunderstood how to download it with github. Forgive my ignorance.

**Comment by bittercranberry** [comment]
No worries, github is weird.
