### ISSUE TITLE
Deity description for Anubis

### ISSUE THREAD

**Issue by Valcarde** [ka-dyn/ExpandedContent#25]
**Describe the bug**
A small change in the description for the Osirian god Anubis:
He is currently described as the 'Guardian of the Timbs'.

**To Reproduce**

Look at the Deity information for Anubis.

**Expected behavior**

Should be "Guardian of the Tombs"

**Comment by FrijDom** [comment]
Nah, Anubis just loves and protects his work boots.

**Comment by bittercranberry** [comment]
Fixed in next update.
