### ISSUE TITLE
Lich Lord of Death localization 

### ISSUE THREAD

**Issue by Lordmitch** [ka-dyn/ExpandedContent#26]
**Describe the bug**
The text for the lord of death is missing text. The player name is missing and the his/her is just a h. The Lord/Lady is just a L.

**Screenshots**
![image](https://user-images.githubusercontent.com/47829580/177406578-dc2b67c5-2ece-4968-9313-0e6de37b6f49.png)

**Comment by bittercranberry** [comment]
Couldn't get it to check gender in the level 1 options, so the description has been updated to be gender neutral.
I will go back and fix if I figure it out in the future but this will do for now.
Will be in the next update.
