### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by Elec0** [ka-dyn/ExpandedContent#28]
**Describe the bug**
When I have this mod installed, along with my other mods, it stays stuck at the initial loading screen forever.

**To Reproduce**
WoTR version: 1.3.7d

My mod list:
> AllowModdedAchievements
BubbleBuffs
BubbleTweaks
BuyMaterialComponents
com.betweentheborders.PWOTR.CombatRelief
EnhancedInventory
FastTravel
FixAlignShift
hotkeysSetAiStealth
MicroscopicContentExpansion
MoreRelicInfo
NoTeleportationCircleRestrictions
RandomEquipment
ScalingCantrips
SparsSorcerousSundries
SpellMetamagicOptionsFix
TabletopTweaks-Base
TabletopTweaks-Core
TabletopTweaks-Reworks
TomeOfTheFirebird
ToyBox
UseUntilHealed
WeaponFocusPlus

I've attached a picture with the versions, since UMM doesn't let you copy easily.

**Screenshots**
You will note that the only mod not enabled is Expanded Content, as that is the only way I was able to get the game to load up.
![image](https://user-images.githubusercontent.com/5119098/179391496-cc6016c8-5d7c-44b3-b60a-39809c463485.png)

**Comment by bittercranberry** [comment]
You are on a old version of the mod, download the update and it should work.
If not could you please get the error log from UMM and I'll have a look.

**Comment by Elec0** [comment]
I...am not sure how that happened. I swore I downloaded the most recent release at least twice.

Anyway, you were right and it works fine now. Sorry about that.
