### ISSUE TITLE
Regarding Seelah's deity

### ISSUE THREAD

**Issue by Naesaki** [ka-dyn/ExpandedContent#30]
It doesn't seem to be effecting anything at the moment (on a fresh / new game), seems to be primarily visual but when I look at Seelah's class ingame. It doesn't show she's selected Iomedae at 'creation'. Can this cause any problems or is it nothing to worry about? As her special abilities still list Iomedae. 

Thank you

![image](https://user-images.githubusercontent.com/91699378/180504589-114253b1-67b3-4c27-acd7-3f96b0a44ad8.png)

**Comment by bittercranberry** [comment]
It's a UI bug, if you look at class features her faith is still their and should work as normal.

I will close this ticket for now but I do have to have a look at sorting the UI in the future just to make it look a bit nicer.
