### ISSUE TITLE
[Suggestion] Ocean's Echo oracle archetype

### ISSUE THREAD

**Issue by Mythalar** [ka-dyn/ExpandedContent#32]
Hello !

First thing first, it's the same request I already made to Vek [here](https://github.com/Vek17/TabletopTweaks-Base/issues/467), since you both added and still ad new archetypes (which are the best feature for me!)
But of course only one is necessary ^^

So here again would you consider adding the [Ocean's Echo](https://www.d20pfsrd.com/classes/base-classes/oracle/archetypes/paizo-oracle-archetypes/oceans-echo-oracle-archetype/) oracle archetype that :
- Loose 1 / 3 / 15 level revelations
- Gain 3 Inspiring Songs as a bard (hence with a tad fewer rounds/day)
- Switch part of Cure/Inflict spells choice for a specific list based mainly on sonic spells (shouts)

Pied Piping is missing but I think Ki Sout would be a good replacement in line with sonic theme (but would require to alter the order since it's one level lower thant Greater shout).

It's not specified per RAW but I would still include the Bardic Performance (Move/Swift) at corresponding levels (it was this way in Kingmaker's mod, I don't remember if it was CotW)

PS : I love the new dragon mystery !

**Comment by bittercranberry** [comment]
Sure I'll give it a look next time I do work on the mod.

**Comment by Mythalar** [comment]
Yeah thanks, singing dragon on its way :p

**Comment by bittercranberry** [comment]
Done, will be in the next update.
I will close this ticket when update releases.

**Comment by Mythalar** [comment]
Whoa that's nice!
