### ISSUE TITLE
[Suggestion] New spell : Symbol of Insanity

### ISSUE THREAD

**Issue by Mythalar** [ka-dyn/ExpandedContent#33]
Hey again :)

Would you consider to implement the [Symbol of Insanity](https://www.d20pfsrd.com/magic/all-spells/s/symbol-of-insanity) spell?

That would give a nice enchantment CC as 8th level spell for Cleric/Oracle, Wizard/Sorcerer and Witch.

For the latter this addition would allow to change the 8th level spell of the Insanity Patron, since as of now its set to Cure Critical Wound, Mass (I don't even know what's the logic here...).

I guess that it would not be such a hassle since Insanity already is ingame.
Diamond powder as material component and a one round incantation (instead of 10min) would not be that powerful in my mind with all mythic powers/spells.

Thanks =)

**Comment by Mythalar** [comment]
Was thinking, about the 8th level of the Insanity Patron : less accurate but the Greater Command spell instead of Cure Critical Wound could be a tad nicer and easier to implement.

Having it as an 8th level spell instead of a 7th is a fair trade off to have a spell of a divine spell list.

**Comment by bittercranberry** [comment]
I am working on tooling for the Symbol/Rune spells but balancing them for a CRPG is proving difficult, which is most likely the reason they are not in the base game in general.

**Comment by Mythalar** [comment]
Yes the "trap" feature is clunky at best and the "not in combat" part is just not an option...
Cannot really see something else than casting time and a shorter range (akin to Greater command or mass hold?)

**Comment by bittercranberry** [comment]
I'm closing this as in DLC5 Owlcat has added all the "trap" spells that work well in a crpg.
