### ISSUE TITLE
start up issues 

### ISSUE THREAD

**Issue by DodecaDerek** [ka-dyn/ExpandedContent#35]
my game wont load when i start it up with this mod, unsure if im missing a recommended file or perhaps did something else wrong, but when i start my game with this mod loaded it simply stops on the opening loading screen. it doesn't crash the game, or freeze, but the purple bar simply doesn't go past half way. i tried leaving it to load for about 45min and nothing changed. any advice or trouble shooting options would be appreciated. 

i have table top tweaks (all 3 parts) installed

**Comment by DodecaDerek** [comment]
![20220814062137_1](https://user-images.githubusercontent.com/111203478/184539093-d34b036c-4890-4ec2-aed4-11058b93f6dd.jpg)

**Comment by bittercranberry** [comment]
Are you using version v0.3.63?
If you are using an older version it may not load.

**Comment by DodecaDerek** [comment]
no im using the newest versions of everything, first thing i tried was reinstalling everything

**Comment by bittercranberry** [comment]
Could I see a screenshot of your UMM and then the error log in game please?

You get the log using ctrl + f10 then log is at the bottom of one of the tabs.

**Comment by bittercranberry** [comment]
Is the issue still there?
If it works please let me know so I can close the ticket.
