### ISSUE TITLE
Idea: Elder Mythos Cultist archetype

### ISSUE THREAD

**Issue by FrijDom** [ka-dyn/ExpandedContent#36]
Since you've added the Elder Mythos as Deity options, I'd like to see the archetype that relies on them added as well. Plus, it would make certain types of clerics easier to build. If you don't want to, that's fine, it's just something I'd like to see as an accompaniment to the new gods.

**Comment by bittercranberry** [comment]
Homebrew Archetypes has already added this, I will at some point make a patch so the mods work a bit nicer together but it does still work.
