### ISSUE TITLE
Oracle, Ocean's Echo can't learn any revelation

### ISSUE THREAD

**Issue by Cairnos** [ka-dyn/ExpandedContent#38]
**Describe the bug**
Hello, a bug for the oracle subclass Ocean's Echo :
I have daeran as ocean echo with Life mystery, upon lvl 7, he can't select any life revelation.

**To Reproduce**
Take Ocean echo and levelup to 7
All revelation are Greyed

Thanks.

**Comment by bittercranberry** [comment]
It seems all bar the dragon mystery are broke, I'll have a look.

**Comment by bittercranberry** [comment]
Should be fixed in an update later today.
Smarter people than me on the discord are to thank for fixing it.

I'll close the ticket once the update is up.
