### ISSUE TITLE
Companion deity selection is not showing up

### ISSUE THREAD

**Issue by abishai** [ka-dyn/ExpandedContent#39]
**Describe the bug**
With this mod active, only PC deity selection is correctly shown, all other companions have a generic icon with question mark. I suspect It's because deity selection UI was changed. If this issue is purely cosmetic, it's OK, What I fear it might break something in game, if deity reference is invalid.

**To Reproduce**
Start a new game with this mod enabled and check Seelah deity in Class view.

**Additional context**
I encountered this bug with Deity feature disabled.

I'm running the following mods:
1. Dark Codex
2. Expanded Content
3. Tabletop Tweaks
4. Respec
5. Bubble Tweaks
6. Bubble Buff

Game version is 1.4.x, compatible version of all mods are installed.

**Comment by bittercranberry** [comment]
This is purely cosmetic for now but it is something I keep an eye on.
If you look in features your selected deity should be there as normal.
