### ISSUE TITLE
Suggestion : Heavens mystery (Oracle)

### ISSUE THREAD

**Issue by Mythalar** [ka-dyn/ExpandedContent#42]
Hey again :)

Since you already quite extended the divine options I would suggest to implement the[ Heavens oracle mystery](https://www.d20pfsrd.com/classes/base-classes/oracle/mysteries/paizo-oracle-mysteries/heavens/)

Quite a few spells are already there or can be approximated if not created : 

- Hypnotic Pattern -> Glitterdust
- Daylight -> Searing light
- Overland flight (would be useful) -> Angelic Aspect ? (Pillar of Life?)
- Meteor Swarm would be a very cool addition I think :p 

Revelations wise, I think the more useful would be : 

- Awesome Display (if possible)
- Coat of Many Stars (on par with other myteries)
- Guiding Star (Perhaps half charisma mod to wisdom skills all the time?)
- Lure of the Heavens (flying immunities, perhaps just a bonus to speed at lvl 10?)
- Spray of Shooting Stars (pew pew !)

The final revelation is close to the enlighted philosopher's I guess.

That's a lot of work, but would complement Ember nicely :p 
And some spells would be useful I think

**Comment by bittercranberry** [comment]
Will be in next update along with Hypnotic Pattern, working on compatibility so if you have the mod with Meteor Swarm it replaces the 9th level spell.

**Comment by Mythalar** [comment]
So nice!
