### ISSUE TITLE
Drake companion footsteps are obnoxiously loud

### ISSUE THREAD

**Issue by kbomb69** [ka-dyn/ExpandedContent#44]
Not sure if this is a base game issue or a mod conflict, so I hesitate to call this a bug with your mod. 

Here's a demonstration comparing the drake to normal movement. Volumes are set to music 0, everything else 100:
https://www.youtube.com/watch?v=tyYdE2cr6Ck

This is with a Claw of the False Wyrm's drake companion.

Here are the other mods I have installed. Strikethroughed mods are disabled ingame: 
https://i.imgur.com/kWit1vh.png

**Comment by bittercranberry** [comment]
My fault for always modding while listening to podcasts, will be fixed in the next update sometime this week.

**Comment by kbomb69** [comment]
No worries! Thanks for the prompt response, it's much appreciated. :)
