### ISSUE TITLE
Oracle, Ocean's Echo Inspire Courage Does not scale with level

### ISSUE THREAD

**Issue by biscay33** [ka-dyn/ExpandedContent#45]
Oracle Oceans's Echo Inspire Courage Does not scale with level
Hello Friend! The Ocean's echo inspire courage ability only confers the +1 to attack and damage even all the way up to level 20 if you take it all the way through. It doesn't seem to scale with level. 

Thanks for making this wonderful mod! If I did not submit enough information, please let me know. I rarely submit bug reports or anything like this so I might have missed something.

**Comment by bittercranberry** [comment]
Fixed, will be in update later today.
I'll leave this open till then, thanks for reporting :)
