### ISSUE TITLE
Divine Subdomain

### ISSUE THREAD

**Issue by knk101** [ka-dyn/ExpandedContent#46]
I think this would be great 😊 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by knk101** [comment]
![image](https://user-images.githubusercontent.com/92350803/190874876-20bd35d2-c995-42cd-9a06-04444d2309ef.png)

**Comment by bittercranberry** [comment]
Wish I could add this but spells do not have a label if they are divine or not, caster can have one but I'm not going to add a label to every caster in the game.
If Owlcat ever add a label I will add this though.
