### ISSUE TITLE
Secrets of Magical Discipline Loremaster feat

### ISSUE THREAD

**Issue by Madcliff** [ka-dyn/ExpandedContent#47]
I think it would be nice to have a way for Loremaster to do something a little more flexible than just having the Spell Secrets Feature

I would deeply appreciate the implementation of the Secrets of Magical Discipline Feat that requires the secret class feature. 
This feat lets you cast any one spell as a one-turn action, once per day, expending a spell slot. If you take the feat additional times you are able to gain additional uses. 

**Additional context**
Details of this feat can be found https://www.d20pfsrd.com/feats/general-feats/secret-of-magical-discipline/

**Comment by bittercranberry** [comment]
With is chaos that is Loremaster stuff I don't want to add anything to do with that class, maybe another modder could help.
