### ISSUE TITLE
Request: Set Group / Group2 on new BlueprintFeatureSelection blueprints

### ISSUE THREAD

**Issue by WittleWolfie** [ka-dyn/ExpandedContent#48]
Logic used in BPCore and TTT generally adds new features to selections by matching the `FeatureGroup`. If a BlueprintFeatureSelection specifies the `Group` or `Group2` fields and the BlueprintFeature has one of those groups it will be added.

I try to keep BPCore updated w/ a list of mod blueprints, including for ExpandedContent so this match can automatically happen. At a glance, Oathbreaker's Teamwork Feat selection should have `FeatureGroup.TeamworkFeat` and there are probably more.

**Comment by bittercranberry** [comment]
I'll have a look at that tonight

**Comment by bittercranberry** [comment]
Looked through the feature selections added, the one you found seems to be the only one, fixed in next update.
Thanks :)

**Comment by WittleWolfie** [comment]
Thank you!
