### ISSUE TITLE
Mythic Drake AC is super effective, too effective.

### ISSUE THREAD

**Issue by teloric** [ka-dyn/ExpandedContent#49]
The drake natural armor bonuses are each stacking with each other instead of replacing each other as it goes up. This results in some over the top AC for the drakes. The example I am attaching has an AC of 131, and of that 102 of it is Drake Natural Armor.

**To Reproduce**
Just level up the drake use the mythic options. (I have not yet tried it nonmythic)

**Screenshots**
![Drake AC](https://user-images.githubusercontent.com/3333909/191703862-3ebae282-49d5-418f-991c-5e52b73872c0.png)

**Additional context**

**Comment by bittercranberry** [comment]
The drakes AC rely on the changes to Natural Armor in TTT, do you have those turned off?
