### ISSUE TITLE
Problems with game start after Update 1.4.4g

### ISSUE THREAD

**Issue by AlexRydi** [ka-dyn/ExpandedContent#50]
After update 1.4.4g game not start with mod. Loadprogression freezes in middle.
All logs in archive.
[GameLogFull.zip](https://github.com/ka-dyn/ExpandedContent/files/9636502/GameLogFull.zip)

**Comment by bittercranberry** [comment]
Update the TableTop Tweaks mods you use and see if that works

**Comment by AlexRydi** [comment]
Thank you, its working.
