### ISSUE TITLE
Can not mount drake

### ISSUE THREAD

**Issue by Joesk** [ka-dyn/ExpandedContent#52]
Don't know if this is a bug or not. But I am now unable to ride it anymore. It says that the Type is NULL when trying to mount the drake.
  I think that it started happening after the v0.3.81 update. So I don't don't know if that was an intended change or not. I have a few other mods, but I was able to mount the Drake till that update. I have two PC's with drakes a small character and a medium. Both were able to ride their drakes. My halfling has been riding since the drake went Medium and my tiefling started riding when his went large.

**To Reproduce**
1. Have drake go to large by leveling up
2. Then try to mount

**Expected behavior**
To ride the drake

![Drakebug](https://user-images.githubusercontent.com/23213189/193104731-f1eb2a05-e1bb-483f-bb8e-40cfca79e949.jpg)

**Comment by bittercranberry** [comment]
Drake riding was not working the way I needed I to, the clipping issues caused a odd amount of problems.
Once I figure out how to do animations I will add proper drake riding, I will change the error message though as that looks rubbish.
Sorry you can no longer ride Balls.
