### ISSUE TITLE
Draconic Druid Compagnion

### ISSUE THREAD

**Issue by pencherek** [ka-dyn/ExpandedContent#53]
**Describe the bug**
The drake is not in the character bar and is named : "Unit not named"

**To Reproduce**
Just create a draconic druid with a drake companion

**Expected behavior**
I expected to have the companion in the character slots

**Screenshots**
https://steamcommunity.com/sharedfiles/filedetails/?id=2869417151

**Comment by bittercranberry** [comment]
That is normal don't worry, this is fixed in ether of two ways, level the drake, or save and reload.
I think I'll make a FAQ document for the next update and this will be included.

**Comment by pencherek** [comment]
thank you
