### ISSUE TITLE
That is normal don't worry, this is fixed in ether of two ways, level the drake, or save and reload.

### ISSUE THREAD

**Issue by pencherek** [ka-dyn/ExpandedContent#54]
That is normal don't worry, this is fixed in ether of two ways, level the drake, or save and reload.
I think I'll make a FAQ document for the next update and this will be included.

_Originally posted by @bittercranberry in https://github.com/ka-dyn/ExpandedContent/issues/53#issuecomment-1263463814_

It is not working, I can't get the drake lvl up window to open and save/reload don't do anything

**Comment by bittercranberry** [comment]
![image](https://user-images.githubusercontent.com/94767653/193275654-b8428f94-448c-47fe-8ec1-028916561a7e.png)
Click the sliver at the bottom of the portrait, the the drake should pop out.
![image](https://user-images.githubusercontent.com/94767653/193275748-ad06c21b-3317-4af9-819f-bb78b259ea86.png)
Please let me know if this fixes it for you, if not can I please have screenshots?

**Comment by pencherek** [comment]
Yes it fixed it, thank you

**Comment by bittercranberry** [comment]
Thanks!
If you find anything else that could be a bug please let me know.
