### ISSUE TITLE
[Class] Aura of Cowardise is sometime not reamoving Fear immunity correctly

### ISSUE THREAD

**Issue by Random-QA-Analyst** [ka-dyn/ExpandedContent#56]
Hello,
I have found another class-breaking issue regarding the Dread Knigh Class
It seems the "Aura of Cowardise" feature is sometime not reamoving Fear immunity correctly, especially on Bosses.

**Step to Repro**
1) Create a Dread Knight character (reproduced myself with Conqueror Archetype but should be the same for all ones)
2) Level-up the character to level 6 (to unlock COrnugon Smash for easier repro) and invest in Intimadation feats/features
3) Activate Power Attack with Cornugon Smash and go to Chorussina fight (don't hesitate to cheat your character with toybox for easier repro or to manually spawn Chorussina with console)
4) Hit Chorussina and notice in Combat log that she is still immune to fear despite the Aura of Cowardise

**Result**
It seems the Aura of Cowardise feature is not working as intended (especially if inspired from the Anti-paladin one).

**Observations :**
Note that Chorussina does not have any magical or buff effect to prevent fear immunity (screen below for details).
On the screen attached below, Regill is a level 10 DreadKnigh-Conqueror
I wonder if Owlcat gave bosses some hardcoded immunity to prevent player to beat them too easily, leading to this issue (which is non-sense to my mind as player does not receive any feedback from those).

**Additional infos**
You will find some screenshot for my game to witness the actual issue (with green-scared higlighted infos).
On my personal run, the issue is occuring on a full respec. Regill .

Best regards and thx you for this wonderful mod

![DK_Bug2](https://user-images.githubusercontent.com/114856142/193449446-a4a1b362-c68b-434d-80d5-7296ea5ca221.jpg)
_Transaltion from frech : 
Regill: Intimidation check-succes
Chorussina is immune to (Shaken)_

Chorussina regular buffs : 
![DK_Bug2 1](https://user-images.githubusercontent.com/114856142/193449928-b6aa13a9-665f-45fa-a9b4-b02dedb241d7.jpg)

Chorussina flat Immunities (including fear-any + Shaken & frightened :
![DK_Bug2 2](https://user-images.githubusercontent.com/114856142/193450036-88b40ea9-2889-4763-8b75-3ac844af952c.jpg)

**Comment by bittercranberry** [comment]
I believe you are correct in thinking some units are hardcoded to be fear immune, I'll do some investigating and see what I can do.

**Comment by Awan1996** [comment]
Is there an example of a unit that doesn't have hard coded immunity? I tried to use dazzling display on some regular zombies but it didn't work.

**Comment by bittercranberry** [comment]
Fixed in next update.

Will close after release.
