### ISSUE TITLE
Strange issue loading on 2.0.1e-hot-fix (October 6 hotfix release for EE)

### ISSUE THREAD

**Issue by DW01** [ka-dyn/ExpandedContent#58]
**Describe the bug**
A friend of mine (she doesn't have a GitHub account so I'm opening this issue on her behalf) is trying to run this mod on the Oct 6 EE hotfix release from GOG (version code 2.0.1e-hot-fix) and is having issues with incomplete load due to the mod seemingly hard-requiring only 2.0.1e_0. Log says it requires 2.0.1e_0 _or later_, but UMM disagrees when the game is loaded.

**To Reproduce**
1. Install via UMM to game version 2.0.1e-hot-fix
2. Wait for the game to load
3. Get hit with an error in the UMM window and a log stating it couldn't load

**Expected behavior**
Mod loads correctly on 2.0.1e-hot-fix from GOG.

**Additional context**
Editing `Info.json` makes the mod load correctly on this version after a GOG Galaxy restart or two, but this is a workaround and may not be reliable.

**Comment by bittercranberry** [comment]
Fixed in the hotfix, thanks for the report :)
