### ISSUE TITLE
Kurgess is listed as having the Community Domain but I can't pick the domain

### ISSUE THREAD

**Issue by ChaoticTabris** [ka-dyn/ExpandedContent#59]
**Describe the bug**
The description of Kurgess lists Community as one of his domains, as it does on tabletop, but upon selecting him as a deity my cleric can't pick the Community domain.

**To Reproduce**
1. Create a Cleric character
2. Pick Kurgess as a Deity
3. Try to select Community Domain

**Expected behavior**
Community domain should be selectable by clerics of Kurgess

**Comment by bittercranberry** [comment]
Fixed, will be in the next update.
