### ISSUE TITLE
Suggestion: Boon - Companion

### ISSUE THREAD

**Issue by Sarakael-RingStar** [ka-dyn/ExpandedContent#60]
Hello!

Currently, it is possible to have a Boon for a Weapon or as a Mount. Would it be possible to add a choice (instead of a mount) of a Fiendish Pet?

**Comment by bittercranberry** [comment]
I'm sorry but I do not understand what this in reference to?

**Comment by Sarakael-RingStar** [comment]
I wrote this little to chaotic and without referencing do class, my apologies. A forgot that You have made more archetypes and classes.

What i mean in previous messege... Dread Knight on 5 lv can choose a Boon (I do not have in time o writing game before me, so names of features/feat may be wrong) either a Boon for Weapon or Boon with Mount. Is is possible to add 3 Boon? Boon to have some Fiendish Companion/pet?

**Comment by bittercranberry** [comment]
I understand now. I'll have to look up what the Anti paladin normally gets but I'll put it on the list of stuff for future updates.
