### ISSUE TITLE
Hellknight Signifier can't progress Dread Knight casting

### ISSUE THREAD

**Issue by Sarakael-RingStar** [ka-dyn/ExpandedContent#61]
**Describe the bug**
Hellknight Signifier recognise you as a divine spellcaster when considering whether you qualify for prestige, but don't allows you to select Dread Knight as the spellbook to progress.

**Comment by bittercranberry** [comment]
Looks like I will need to add both dreadknight and the Claw archetype spellbook blueprints, I will try to get this done some time this week.
I'll leave the ticket open until then.
