### ISSUE TITLE
No mention of Unridable dragons

### ISSUE THREAD

**Issue by mishona** [ka-dyn/ExpandedContent#62]
Attempting to mount a dragon while under the effects of Reduce Person to be small enough yields the error "Target Has Feature Not Available". This was tested with a Claw of the False Wyrm/Cavalier multiclass.

Also, barding is unavailable to select, but weapon proficiencies are.

**Comment by bittercranberry** [comment]
I disabled mounting as there are no animations so the unit glitch into each other and cause problems, I will update the FAQ on nexusmods to reflect this.

Barding is disabled on purpose as drakes cannot wear barding per the tabletop rules.

**Comment by FrijDom** [comment]
Important correction; They *can* wear barding, but they *won't*. This is important because barding absolutely can be made to fit a drake or small dragon, but they will never wear it.
