### ISSUE TITLE
Profane Resilience not updating with charisma changes.

### ISSUE THREAD

**Issue by mishona** [ka-dyn/ExpandedContent#64]
Dread Knight's Profane Resilience doesn't appear to update when charisma changes. The Conqueror archetype is used, if that makes a difference.
![Wrath_B2snGM299T](https://user-images.githubusercontent.com/50522719/195471681-f07459e9-bb88-46c8-8dd9-e6814d9903dd.jpg)

**Comment by bittercranberry** [comment]
Fixed will be in the bug fix, will leave open until then.
Thanks for the report!
