### ISSUE TITLE
Invoke Deity - Glory Domain Positive Damage Instance

### ISSUE THREAD

**Issue by knk101** [ka-dyn/ExpandedContent#65]
**Describe the bug**
The additional 1d6 Positive Damage against undead for the Invoke Deity Glory Domain is acting as a separate damage instance and recieving additional dice from Sword of Heaven, Bane, Inveitable Fate etc. 
I don't think this is intended behaviour (it is really OP).

**To Reproduce**
1. Go to Invoke Deity - Glory Domain
2. Activate ability 
3. Attack Undead
4. Refer combat log

**Expected behavior**
The additional damage 1d6 is added to the weapon attack only in the same manner as flaming enchant enchant etc

**Screenshots**

![glory domain invoke deity](https://user-images.githubusercontent.com/92350803/195736242-b0edc705-fff6-4ee6-a22c-ec981f3a378a.png)

**Additional context**

**Comment by bittercranberry** [comment]
Ok that is a bit daft, I'll see what I can do over the weekend, thanks for the report.

**Comment by bittercranberry** [comment]
I've had time to look into this and oddly other features worded as "deals an additional 1d6 points of XXXX energy damage." such as the elemental bloodrager melee feature work in the same way.
So while I agree with you that it doesn't seem like it should work like this, Owlcat have said it does.

Plus it's only on 1 attack per round (unlike the bloodrager feature that is on every attack) and only on undead, so I guess you get to keep the extra damage.
