### ISSUE TITLE
Temple Champion - Sun's Blessing

### ISSUE THREAD

**Issue by knk101** [ka-dyn/ExpandedContent#66]
**Describe the bug**
The Sun Domain Sun's Blessing feature which adds the level in the class that grants the domain to Channel Positive Energy - Damage Undead is not working for the Temple Domain Archetype. 

**To Reproduce**
1. Select temple champion archetype
2.Select Sun Domain (i selected it as the second domain)
3. Channel Positive Energy to damage undead
4. Refer channel positive energy damage in the combat log. note, no "sun's belssing: character level" in the 'other damage section.

**Expected behavior**
The feature should cause bonus damage to undead when channeling equal to character level. 
This bonus damage should be visible in the combat log under 'other'. 
**Screenshots**
See below bugged behaviour done on level 20 temple champion:
![SUN DOMAIN TEMPLIE CHAMPION](https://user-images.githubusercontent.com/92350803/195767094-fce1a1da-189c-406a-bc1d-01928bce7b1a.png)

See below correct behaviour on a cleric with the sun domain feature.
![SUN DOMAIN - CLERIC](https://user-images.githubusercontent.com/92350803/195767160-f491c155-517a-4a5b-b934-e334338dae97.png)

**Additional context**

**Comment by bittercranberry** [comment]
I'll look into this on the weekend, thanks for the report.

**Comment by bittercranberry** [comment]
Fixed in next update, will leave issue up until release.
