### ISSUE TITLE
Drake Companion (Draconic Scholar) have no spells

### ISSUE THREAD

**Issue by Sarakael-RingStar** [ka-dyn/ExpandedContent#67]
**Describe the bug**
The Drake Companion has no spells, and it seems it should.

**To Reproduce**
Steps to reproduce the behavior: Just create a Draconic Scholar with a Drake Companion. Next levelup your companion.

**Expected behavior**
When you level up your Companion, a spell selection window will appear and there are no spells.

**Additional context**
I haven't tested with other Archetypes and Drakes, but it is possible that the problem will be similar.

**Comment by bittercranberry** [comment]
This is intentional, taking the right drake powers and the mythic drake ability will unlock the spellcasting.
If you do not get spellcasting after that, please reopen this ticket
