### ISSUE TITLE
Touch of Corruption not applying cruelty

### ISSUE THREAD

**Issue by mccabefliam** [ka-dyn/ExpandedContent#69]
**Describe the bug**
They fail the save and gain no status effect from any cruelty

**To Reproduce**
1. Attack with cruelty
2. Check to see if they failed the save
3. Check status of enemy
4. See that there is no status effect applied

**Expected behavior**
Feared, sickened or other status effect applied

**Comment by mccabefliam** [comment]
![Screenshot 2022-10-23 134133](https://user-images.githubusercontent.com/15720886/197407212-df929cdb-465f-43a8-9b28-3fa8fbf14ed9.png)

**Comment by mccabefliam** [comment]
As an example I tried using sicken on this and it doesn't have immunity to sicken. Ive tried all my cruelties out including fear which nothing should be immune to.

**Comment by mccabefliam** [comment]
![image](https://user-images.githubusercontent.com/15720886/197407584-a80bd315-4a70-46c6-981a-96cecb33338c.png)
Example of me trying it with fear in another playthrough without the conquerer archtype.

**Comment by mccabefliam** [comment]
![image](https://user-images.githubusercontent.com/15720886/197408947-76b7c1f9-9f23-4797-9ffa-d6fd33b75356.png)
Not even working on a basic cultist

**Comment by bittercranberry** [comment]
The silly thing is that I have fixed this before, I don't know what changed and won't be able to get time for a look for a day or two.
Any chance it worked in the past and broke suddenly, or has it never worked in your game?

**Comment by mccabefliam** [comment]
No I tried it again a few more times today and tried turning off other mods with no luck. Thanks for looking into it. Will just put these play throughs on hold till you get a chance to find the issue. Love your mod btw and am excited to play with it more.

**Comment by bittercranberry** [comment]
![image](https://user-images.githubusercontent.com/94767653/197653630-c330d2df-1137-4566-a154-257421c79cf0.png)
Fixed! One of the last updates broke every single one, so I won't be able to update until I have more the the 20 or so min today to sort them all out.

Thanks for your testing it was a big help, if there is anything you want from the tabletop that I might be able to add let me know.

I'll leave this ticket open until the update is out.

**Comment by mccabefliam** [comment]
Happy to help! Content mods like yours make this game way more replayable and its always a pleasure to see new ones coming up. 

" if there is anything you want from the tabletop that I might be able to add let me know."

I know it would be a big ask, but I've been desperate for some psychic class/ archtypes from pnp. I loved playing it with "Call of the Wild" in kingmaker, and was sad to see no one adopt the class/ psychic archtypes yet for Wotr. Other than that more gish archtypes are always fun like the Blade Adept Archanist :)

**Comment by bittercranberry** [comment]
Updates out, one day I might be brave enough to try the psychic stuff but not yet.
I believe another modder is doing the blade adept archetype so I'll hold off on that for now.

Once again, thanks for the help!
