### ISSUE TITLE
Request: More Occult Classes

### ISSUE THREAD

**Issue by Nerin3** [ka-dyn/ExpandedContent#70]
Currently, the only psychic class we've got is Kineticist, compared to other divine and arcane classes the choice here is non-existent. I was wondering if it was possible for you to implement more classes from Occult Adventures book. Like Psychic, Mesmerist or others from the book?

**Comment by bittercranberry** [comment]
We will not be adding those classes in this mod, however a mod is in development that is planning to add some occult content. You might be waiting a bit but the first class planned is the Psychic.
