### ISSUE TITLE
Dreadknight Fiendish Boon

### ISSUE THREAD

**Issue by Pgasus9412** [ka-dyn/ExpandedContent#71]
Hello,
I have found an issue regarding the Dread Knigh Class.
For a character whose class is Dread Knight, after upgraded to level 5, if Fiendish Servant was chosen from Profane Boon ability, a bug will occur and this character can not choose any class with variants later after being upgraded.

1. Create a Dread Knight character
2. Level-up the character to level 5 and choose a Fiendish Servant from Profane Boon.
3.  Level-up the character to level 6
4. Choose any other Class with variants,and you will find that it's impossible because the game will force you to choose the vanilla version of this Class.(For example,if you want to choose Scaled Fist,the game will force you to choose its vanilla version:Monk)

Environment:
Game version:2.0.3i
Mods:
ExpandedContent v0.4.3
TabletopTweaks-base v2.4.3
Homebrew Archetypes v1.1Zth

Screenshots:
The role before upgarde:
![image](https://user-images.githubusercontent.com/78341779/200505875-0613ce2e-640a-43df-85a1-ef8b63d48f6b.png)
When upgrade to Level 5,a class with variants can be choosed:
![image](https://user-images.githubusercontent.com/78341779/200506346-e37fd005-4ac9-4c30-b907-c34c4e5c1219.png)
So far it works fine:
![image](https://user-images.githubusercontent.com/78341779/200506809-5a012d7e-c6f9-4118-8c73-07a17451b1ff.png)
The bug occurs here,when Dread Knight Class upgrade to Level 5:
![image](https://user-images.githubusercontent.com/78341779/200507074-3498da6a-fb0e-48a9-8802-76992fed476d.png)
After this level I can choose class with variants no more:
![image](https://user-images.githubusercontent.com/78341779/200508082-6251ca10-8e2a-4e4b-bda5-e790c98975ba.png)
When I select Bloodrider,my selection will suddenly forced to change Bloodrager.

Extra BUG:
Dread Knight cant choose Animal Companion if he already had one.
But when the same situation happens to Paladin it woks different.
![image](https://user-images.githubusercontent.com/78341779/200509417-3f16143f-e371-452c-a9fc-d80a07a77440.png)

Result:
This bug seems to have been reported at Nexusmods,I‘m here to provide more detailed information.

**Comment by bittercranberry** [comment]
Both of these have been fixed for the next update, I will close this ticket when I update.

If the bugs remain on your game after the update (and a full respec) then feel free to reopen the ticket and I will continue investigating.
