### ISSUE TITLE
Invoke deity - healing domain

### ISSUE THREAD

**Issue by knk101** [ka-dyn/ExpandedContent#73]
Upon using the ability the fast healing 3 does not occur. caster level increase does not appear to occur either but this may be because of the per caster level cap on the heal, I am not sure.

If it is relevant the deity chosen is sarenrae.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by bittercranberry** [comment]
Caster level seems to work fine, I have fixed the fast healing for the next update.
I'll leave the ticket open until next release.
