### ISSUE TITLE
Aivu class for Aivu please. Levelable Aivu in Expanded Content

### ISSUE THREAD

**Issue by jedi7000nathan** [ka-dyn/ExpandedContent#74]
As of the the most recent patch for WOTR Levelable Aivu no longer works and I'm not sure if it is even maintained, would it be possible to integrate the features of that mod into Expanded Content for a consistent thing, Aivu's already a pet option in Expanded Content and I'd like to see Aivu via the mythic path get a similar treatment as in actually being able to control her level ups and what she gets. Its a real gripe on my end and that of any Azata players especially given well Owlcat rebalancing gimping her.

**Comment by bittercranberry** [comment]
Sorry but making Aivu levelable is not the kind of thing I want to put in this mod as it messes with base game content.
