### ISSUE TITLE
Suggestion - Adding Heavens Spirit to Shamans

### ISSUE THREAD

**Issue by ForestDragonCat** [ka-dyn/ExpandedContent#79]
With recent addition of Oracle Mystery - Heavens, is it possible to also add its Spirit equivalent for Shamans, since they are almost identical? With possible support for Mystical Mayhem's Manifestations?

https://www.d20pfsrd.com/classes/hybrid-classes/shaman/spirits/heavens/

**Comment by bittercranberry** [comment]
I'm not sure how the Sprits tie into other features, but I'll have a look.

**Comment by bittercranberry** [comment]
Took a while but it is added.

**Comment by ForestDragonCat** [comment]
> Took a while but it is added.

O-o-oh, thank you so much, you are the coolest! All the luck for your future works <3
