### ISSUE TITLE
Pulura Titles Loc

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#80]
**Describe the bug**
Pulura is missing "Titles" before her list of titles. Also there is an extra space after the sentence ending "far north" in the description. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47829580/208184657-1265d7b4-0b45-4db7-ad88-85fe3146f311.png)

**Comment by bittercranberry** [comment]
Fixed for next update. 
I will close when the update is out.
