### ISSUE TITLE
Naderi missing line break

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#82]
**Describe the bug**
Naderi is missing a line break between Sacred animal and the description. 

**Screenshots**
![image](https://user-images.githubusercontent.com/47829580/208216226-06b82297-0734-4f37-80c7-f6938d7af924.png)

**Comment by bittercranberry** [comment]
Fixed, thanks for finding a bunch of these! If you find any more and what to save yourself time you can dm me in the owlcat discord.
Will remove issue in next update.
