### ISSUE TITLE
Gods Loc errors 

### ISSUE THREAD

**Issue by Lordmitch2** [ka-dyn/ExpandedContent#85]
**Describe the bug**
Daikitsu and Tsukiyo need a line after there Sacred Animal.
Ketephys needs a space after the sentence ending "own skill.".
Jaidz needs a space after the sentence ending "own potential" and a space after the comma after "be helped".
Jalaijatali has a space between "scales" and the full stop at the ending of the sentence. 
Lalaci has glass misspelled near the end as "gla s s".
Ragathiel needs a space after the sentences ending "layer of Hell", "shield them" and "silver clothing".
Tolc has a space between "harsh elements" and the full stop at the ending of the sentence. 
Valani needs a space between "of" and "Fireshaker" near the end. 

This is the errors with the Gods loc that I can find.

**Screenshots**
![image](https://user-images.githubusercontent.com/47829580/211461617-c9e90325-02a0-4563-83f2-d0ffe3df846c.png)
![image](https://user-images.githubusercontent.com/47829580/211463489-7357a661-60ed-4bf5-a5d0-50fefa9f9f01.png)
![image](https://user-images.githubusercontent.com/47829580/211463635-c4a48587-85e3-4a8c-a092-1d7a51abe176.png)
![image](https://user-images.githubusercontent.com/47829580/211463977-a21b4160-b976-4160-878a-4f1d6d60d8ed.png)
![image](https://user-images.githubusercontent.com/47829580/211464443-58b79ae1-830b-4715-bd92-8528eed115d1.png)
![image](https://user-images.githubusercontent.com/47829580/211464711-e8556224-a5d4-40ff-a365-0f35dbb3287d.png)
![image](https://user-images.githubusercontent.com/47829580/211465162-4f734271-e4f2-4790-836c-dfe030f13674.png)
![image](https://user-images.githubusercontent.com/47829580/211465523-71e8cc66-7391-42a3-9a35-a8f1d202320c.png)
![image](https://user-images.githubusercontent.com/47829580/211465714-f6d6bbd6-5278-42f2-bcb8-a0f730054f30.png)

**Comment by bittercranberry** [comment]
All fixed in the newest update, thanks so much for finding these I am terrible at proofreading.
