### ISSUE TITLE
Newest update

### ISSUE THREAD

**Issue by Gwendovescry** [ka-dyn/ExpandedContent#86]
I updated the file this morning and then noticed that i could not use shops anymore. I saved and reloaded, same deal. I reverted back to the last version and reloaded and I could shop fine. With the newest version it lets me put items in the trade window, but doesn't adjust prices or enable the trade button.

**Comment by bittercranberry** [comment]
I am not having this issue, could you redownload the mod and try again so me please?
If it is still happening a list of your mods and the location of the shop with the problem would be helpful.

**Comment by bittercranberry** [comment]
Unable to replicate.
