### ISSUE TITLE
Suggestion - Heroism and Defense Subdomains

### ISSUE THREAD

**Issue by Ardencroft** [ka-dyn/ExpandedContent#89]
Would love to try buff cleric with greater heroism and encouraging spell, and the Defense Subdomain has the most insane spell list for a gish that I'd like to try it as well.

**Comment by bittercranberry** [comment]
I actually got half way through writing the Heroism Subdomain before realising that it's already in the game, they just called it Glory Domain as they couldn't get the Glory level 8 ability to work.

As for Defence, it is on the list but I delayed it until I could figure out how to get the Deflection spell to work. I'll try to add the subdomain soon but chances are it will not have that spell for now.

**Comment by Ardencroft** [comment]
I really wanted Glory Domain not for the power, wanted it for greater heroism being on the spell list, as its normally not a cleric spell, but Im excited to see Defense anyway!

**Comment by bittercranberry** [comment]
Both are added, will be in the next update.
