### ISSUE TITLE
Oathbreaker's Direction not progressing its bonus

### ISSUE THREAD

**Issue by nemkrisz11** [ka-dyn/ExpandedContent#9]
**Describe the bug**
Oathbreaker's Direction does not progress its attack/damage bonus on levelups.

**To Reproduce**
1. Create a character with the oathbreaker class
2. Level up to level 5
3. Use Oathbreaker's Direction on an enemy
4. Hit the enemy and see that the Oathbreaker's Direction bonus is still +1, when it should be +2.
5. Do the same at level 10.

**Expected behavior**
Oathbreaker's Direction advances its bonus by 1 on level 5, 10, 15, and 20.

**Comment by knightddk** [comment]
still not fix, interesting

**Comment by Cairnos** [comment]
> still not fix, interesting well i think here？
> 
> bp.AddComponent(c => { c.ValueType = AbilitySharedValue.DamageBonus; c.Value = new ContextDiceValue() { DiceCountValue = 0, BonusValue = new ContextValue() { ValueType = ContextValueType.Rank, ValueRank = AbilityRankType.DamageBonus, ValueShared = AbilitySharedValue.DamageBonus, } };
> 
> ```
>                 c.Modifier = 1;
>             });
> ```

Hello,

Could you specify which file to modify and where do you add your line.

Thanks.

**Comment by bittercranberry** [comment]
Fixed in next update, will leave open until then.

**Comment by knightddk** [comment]
> Fixed in next update, will leave open until then.

thx
