### ISSUE TITLE
New spells non eligible for Completly normal spell metamagic

### ISSUE THREAD

**Issue by Mythalar** [ka-dyn/ExpandedContent#90]
Hello,

As title, it seems that all new spells I could learn are not eligible to the Trickster Completly normal spell metamagic feat.

As a side not : are the new spells not optional in UMM menu since they can be used with new domains?
Asking since I have quite a few duplicates with all mods (TTT added Inflict pain yet again this morning :p )

**Comment by bittercranberry** [comment]
I'll have a look into the metamagic thing. Yes the reason is I would need to find other spells to put in the domains and often the whole reason I made the spell is because I had no alternatives to put there.

**Comment by Mythalar** [comment]
No prob, there cannot be too much spells!

**Comment by bittercranberry** [comment]
I've fixed the meta magic thing, to remove duplicate Inflict Pain please disable the option in TTT
