### ISSUE TITLE
Suggestion: A Separate Dragon-Companion

### ISSUE THREAD

**Issue by Necht** [ka-dyn/ExpandedContent#92]
Hi! I'm very interested in dragon companions, but I don't want to load my game with content that I don't use. If possible, could you make a separate mod that will only have dragons?

**Comment by bittercranberry** [comment]
No sorry, that's time I would rather spend adding more stuff.
You should just be about to ignore the other features as they do not effect gameplay if you do not pick them and most can be made invisible in the mod menu.
